### ISSUE TITLE
Don't show 'stop' indicator when user has already stopped the timer

### ISSUE THREAD

**Issue by pe0ny** [toggl/stopwatch#19]
When user stops the timer first time before the indicator appears (within 5sec), then don't show plusing circles anymore.

Otherwise this happens:

![img_0770](https://cloud.githubusercontent.com/assets/5064445/16257904/e6d31a3e-3863-11e6-826f-dae8306a132e.PNG)

**Comment by eroshin** [comment]
Fixed.

**Comment by amulware** [comment]
Closed by #32.
