### ISSUE TITLE
Rate and review selection to the app

### ISSUE THREAD

**Issue by pe0ny** [toggl/stopwatch#23]
Show this when:
User has at least 10 time entries total AND user has tracked time entries in a 3 different days
(eg if user tracked 10 time entries in a row, we do not show rating popup!)
And show rating popup after user stopped the timer. Don't show popup when timer is running or is paused. Also, don't show popup right after user opened the app.

1) First we'll ask: "**Enjoying Stopwatch?**"
with two options: "Not really" and "Yes!"

If user picks "**No really**", we'll show different question requesting their feedback:
"Would you mind giving us some feedback?"
with two options: "No, thanks" and "Ok, sure"

If user picks "**Yes**", we'll ask them for a rating:
"How about a rating on the App Store?"
with two options: "No, thanks" and "Ok, sure"
"No, thanks" - we won't bother user anymore
"Ok, sure" - direct users to app store

2) If user picks to give us some feedback by tapping "Ok, sure", we'll direct users to feedback form.
If user picks not to give us feedback by tapping "No, thanks", we'll close the questions/popups

**Comment by pe0ny** [comment]
designs are needed!

**Comment by amulware** [comment]
We also need to determine what to do with the data entered into the feedback form.

**Comment by pe0ny** [comment]
Send the data to support@toggl.com same way Toggl ios app does

**Comment by pe0ny** [comment]
Flow:

First ask:
![toggl stopwatch - rating - first question](https://cloud.githubusercontent.com/assets/5064445/17664577/caac3bd2-62fd-11e6-9eab-36f7d15b2ed5.png)

If "Yes", then ask next question:
![toggl stopwatch - rating - positive answer](https://cloud.githubusercontent.com/assets/5064445/17664587/db8b6aa4-62fd-11e6-8bb8-073d47e95a9d.png)
If user agrees again, then direct user to app store for giving review
If not then close the popup

If user answers "Not Really" first time, then ask another question:
![toggl stopwatch - rating - negative answer](https://cloud.githubusercontent.com/assets/5064445/17664612/fcd686da-62fd-11e6-9347-442f3954c4ad.png)

If user agrees, then ask feedback:
![toggl stopwatch - feedback](https://cloud.githubusercontent.com/assets/5064445/17664616/05cf79a4-62fe-11e6-837e-c13151a9c629.png)
If not then close the popup


Check Zeplin for additional info

**Comment by pe0ny** [comment]
Check Zeplin for light theme colors!

**Comment by amulware** [comment]
@pe0ny Except for the message the user enters, what other kind of data do we want to send? For example.. the number of time entries they have? How often they have started the app, or when they started it first, or something like that? - I guess the latter may be a bit pointless, given the constraints on when to show this screen.

Since backend has to create a separate endpoint for this, it would be good to know what we'll want of this.

Of course, we can always append more info to the main text body, which may be the easiest in any case.

**Comment by pe0ny** [comment]
I would say that the message the user enters is good enough.
Since we know that they have at least 10+ TE and they've been using it more than three days. Most probably this feedback is negative and we want to know why.

**Comment by cwliu** [comment]
@pe0ny About the feedback input screen, Do we intend to have no cancel button on this screen?  so that user must input some text to close this.

**Comment by pe0ny** [comment]
@cwliu Good point! 👍 Let's add 'Cancel' Button there:

![toggl stopwatch - feedback](https://cloud.githubusercontent.com/assets/5064445/17732396/2a69c076-647a-11e6-8937-f3003127703c.png)

**Comment by amulware** [comment]
If the user decides to send feedback, the message will be POSTed to a new endpoint backend will implement for us.

Authorisation will happen (in the http header) using a secret magic number/password embedded in the stopwatch app code, which backend will provide. This number will not be visible in this public repository, instead we will keep it secret and insert it into the code only when building builds using the same/similar scripts to the one used in the mobile app to replace secret values.

Messages will be a simple JSON object with a single string field:

```
{
    "message" : "the message the user entered as a multi-line string (make sure special characters are escaped properly)"
}
```

To make things clear do support people handling these messages and maybe enable automatic handling, let us prepend the message with:

```
Toggl Stopwatch v1.1.0 Feedback\n\n
```
Obviously with the current version number of the app, and actual new-lines at the end.

**Comment by amulware** [comment]
wip here: #46

**Comment by pe0ny** [comment]
We also need some metrics here:
- [ ] Number of likes and dislikes (responses to the first question)
- [ ] Number of how many agreed and disagreed to rate the app

**Comment by sofokli1** [comment]
@pe0ny are the following paths correct? If not please let me know.
```
Enjoying (Yes!) > rate on app store (Ok, sure) > go to app store
Enjoying (Yes!) > rate on app store (No, thanks) > give some feedback (Ok, sure) > feedback composer
Enjoying (Yes!) > rate on app store (No, thanks) > give some feedback (No, thanks) > hide everything
Enjoying (Not really) > give some feedback (Ok, sure) > feedback composer
Enjoying (Not really) > give some feedback (No, thanks) > hide everything
```

**Comment by pe0ny** [comment]
@sofokli1 almost :)


Enjoying (Yes!) > rate on app store (Ok, sure) > go to app store
Enjoying (Yes!) > rate on app store (No, thanks) > ~~give some feedback (Ok, sure) > feedback composer~~ **hide everything**
Enjoying (Yes!) > rate on app store (No, thanks) > ~~give some feedback (No, thanks) > hide everything~~ **hide everything**
Enjoying (Not really) > give some feedback (Ok, sure) > feedback composer
Enjoying (Not really) > give some feedback (No, thanks) > hide everything
