### ISSUE TITLE
Show log-hint

### ISSUE THREAD

**Issue by pe0ny** [toggl/stopwatch#29]
Show log-hint after user has created his first time entry (timer has been started and stopped).
Show log-hint only once. When user has opened log, don't show the hint anymore.

![toggl stopwatch - timer - light - with swipe indicator](https://cloud.githubusercontent.com/assets/5064445/17509608/7d8abfec-5e23-11e6-823b-3c3bb782ef5f.png)

**Comment by amulware** [comment]
#32
