### ISSUE TITLE
New description and keywords in app store

### ISSUE THREAD

**Issue by pe0ny** [toggl/stopwatch#30]
We need new description (max 4000char) and keywords (max 100char).

Current ones: "Simple stopwatch app for tracking time. Use the stopwatch to start and stop the timer. Shake the phone to reset."

and keywords: "stopwatch, timer, time tracker, time tracking, productivity, online stopwatch, offline stopwatch"

**Comment by annikatoggl** [comment]
Desc: Best simple stopwatch app with great UI/UX for tracking time. Use the stopwatch to start and stop the timer. Shake the phone to reset. Perfect for simple work task logging or productivity tracking. 

keywords: stopwatch, timer, time tracker, time tracking, time logger, time logging, work timer, task timer
